pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile python-code-project/script.py python-code-project/test.py'
                stash(name: 'compiled-results', includes: 'python-code-project/*.py*')
                sh 'ls -l python-code-project'
            }
        }
        stage('Test') { 
            agent {
                docker {
                    image 'qnib/pytest' 
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml python-code-project/test.py' 
                sh 'cat test-reports/results.xml'
            }
            post {
                always {
                    junit 'test-reports/results.xml' 
                }
            }
        }
    }
}